### ISSUE TITLE
Higher version than 0.0.4 will not work with exporting test coverage

### ISSUE THREAD

**Issue by rH4rtinger** [microsoft/vscode-test-cli#24]
I had a problem, when I tried to export the coverage of my extension via c8.

I found out that the problem was the too new version of the `@vscode/test-cli` dependency.

# Steps to reproduce

## Setup the project
1. Create a new project with ` yo code`
2. Install c8 for coverage `npm install --save-dev c8`
3. Add in the package.json a coverage script: 
```json
 "scripts": {
    "vscode:prepublish": "npm run compile",
    "compile": "tsc -p ./",
    "watch": "tsc -watch -p ./",
    "pretest": "npm run compile && npm run lint",
    "lint": "eslint src --ext ts",
    "test": "vscode-test",
    "coverage": "c8 npm run test"
  }
 ```

I also added a sample method to my `extension.ts`:

```typescript
export function add(a: number, b: number): number {
  return a + b;
}
```

I added a test for this method in my `extension.test.ts`:

```typescript
suite("add", () => {
  test("should add 1 and 2", () => {
    assert.strictEqual(3, add(1, 2));
  });
});
```

## Expected behavior

When I execute `npm run coverage` with the dependency `"@vscode/test-cli": "^0.0.4"`, then everything works.
I can see the coverage  in my output.
![image](https://github.com/microsoft/vscode-test-cli/assets/116057830/6e221d52-2f67-4d2f-8e3a-14d7a7daae5d)

## Actual behavior
When I execute `npm run coverage` with version of  `@vscode/test-cli`  set to 0.0.5 or 0.0.6, then my coverage is not visible
![image](https://github.com/microsoft/vscode-test-cli/assets/116057830/033dbd22-155a-4b23-aa90-7215035fcda2)

**Comment by leep-frog** [comment]
I'm experiencing a similar issue except it doesn't work with any version.  I also use `c8` and tried different versions, but my coverage reports never produce the proper coverage info (coverage report shows all lines except class and function definitions as untested)

**Comment by connor4312** [comment]
Can you just run `vscode-test --coverage` without invoking c8?

**Comment by connor4312** [comment]
Yes, I have it on my plate this month to flesh out the documentation a lot more. Thanks for confirming the --coverage option works for you, I'll close this issue. Let us know if you have any other questions!
