### ISSUE TITLE
Coverage file shows two test files

### ISSUE THREAD

**Issue by leep-frog** [microsoft/vscode-test-cli#36]
## Configuration

I have the following vscode test configuration:

```
// package.json
// ...
"scripts": {
    // ...
    "pretest": "npm run compile",
    "test": "vscode-test --coverage --coverageReporter lcov --coverageReporter html",
    "test-compile": "tsc -p ./",
  },
```

```
// .vscode-test.mjs

import { defineConfig } from '@vscode/test-cli';
import path from 'path';

export default defineConfig({
	files: 'out/test/**/*.test.js',
  useInstallation: {
    fromMachine: true,
    fromPath: path.resolve(".vscode-test", "vscode-win32-x64-archive-1.87.0", "Code.exe"),
  },
  workspaceFolder: path.resolve("src", "test", "test-workspace"),
  env: {
    VSCODE_STUBBABLE_TEST_FILE: stubbableTestFile,
  },
  mocha: {
    timeout: 60000,
  },
});
```

## Actual Behavior

After running `npm run test`, the auto-generated coverage file (`index.html`) output file produces the following:

> Note the duplicate lines for each file (aside from `extension.ts`)

![image](https://github.com/microsoft/vscode-test-cli/assets/66687468/7f7e4790-d021-41e6-9c4d-01cb675a10d8)

## Expected Behavior

I would expect there to only be one row per file.  My best guess is that the coverage reporter tracks coverage on (1) files that are running locally (e.g. testing local methods) and (2) the same files that are running as part of the new VS Code window that is opened for the test execution. 

> I'm not actually testing any methods locally in this test suite, so it's mostly just coverage for function/variable declarations.

Would it be possible to either ignore the former type of coverage and/or to merge the coverage files?

**Comment by connor4312** [comment]
Duplicates  https://github.com/microsoft/vscode-test/issues/136

**Comment by leep-frog** [comment]
Thanks for the redirect.  I confirmed that this indeed was the issue by adding `console.log(__filename)` in one of my files and saw two outputs (note the casing of `C;\`):

```
C:\...\find.ts
c:\...\find.ts
```

so the issue you linked to is indeed the culprit.  Just wanted to confirm for anyone else who stumbles upon this issue.

Thanks!
