### ISSUE TITLE
Add env file support

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-test-cli#47]
Similar to how debug launch configurations support env files, it would be nice to support env files in `.vscode-test.mjs`.

**Comment by connor4312** [comment]
Note that on Node 20 you can pass `node --env-file=.env ...` but this is awkward when calling a CLI app

**Comment by connor4312** [comment]
I'm not sure I plan to do anything special here, it's easy enough for folks who want this to grab [`dotenv`](https://www.npmjs.com/package/dotenv) and pass that in their configs.
