### ISSUE TITLE
Mocha drive letter case sensitivity bug

### ISSUE THREAD

**Issue by lovettchris** [microsoft/vscode-test-cli#49]
I found a mocha bug that is fixed with the following hack, so you might want to add this to your sample `index.ts` files:

```typescript
export function run(testsRoot: string, cb: (error: any, failures?: number) => void): void {
    // Create the mocha test
    const mocha = new Mocha({
        ui: 'tdd'
    });

    if (process.platform === 'win32') {
        // workaround for https://github.com/microsoft/vscode-test/issues/134
        // see also https://github.com/mochajs/mocha/issues/4851
        testsRoot = testsRoot.toLowerCase();
    }
```

**Comment by eliericha** [comment]
Hello folks,

Is there a release of `@vscode/test-cli` planned soon to benefit from this fix?

Thanks

**Comment by connor4312** [comment]
0.0.10 was released with this fix

**Comment by eliericha** [comment]
I see that the Extension Test Runner version 0.0.10 has been released, but I don't see a release of the [@vscode/test-cli](https://www.npmjs.com/package/@vscode/test-cli?activeTab=versions) npm package. Will that also be released any time soon?

Thanks

**Comment by connor4312** [comment]
Ah, sorry, forgot to trigger the build for that. Should be out in a few minutes.
