### ISSUE TITLE
Add support for installing dependent extensions

### ISSUE THREAD

**Issue by 50Wliu** [microsoft/vscode-test-cli#5]
This CLI looks like a great improvement and I'd love to start incorporating it into our own extensions. However, it seems like it's missing support for [installing extensions](https://code.visualstudio.com/api/working-with-extensions/testing-extension#custom-setup-with-vscodetestelectron), which we need as we depend on (for example) the [.NET Install Tool](https://github.com/dotnet/vscode-dotnet-runtime/tree/main/vscode-dotnet-runtime-extension#net-install-tool).

It would be great if the CLI could take in an array of extensions to install - or, even better, automatically install any extensions listed under `extensionDependencies` in the extension manifest.

**Comment by JustinGrote** [comment]
Agreed. There are two workarounds now I can think of:
- Use a temp profile and add it to your launchArgs of the config e.g. "--profile=TestCLI" and then manually install your extensions there.
- Use a PreLaunchTask to add the extensions to the downloaded profile
