### ISSUE TITLE
Does not actually support .cjs extension for config despite docs saying so

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode-test-cli#51]
![image](https://github.com/microsoft/vscode-extension-test-runner/assets/15258962/aaa3c8ae-bffe-4aac-ab06-47561f82e631)

![image](https://github.com/microsoft/vscode-extension-test-runner/assets/15258962/2b5c79c1-9426-4f9a-a11d-d9abc47348b3)

`Error: Could not read .vscode-test configuration: I don't know how to load the extension 'cjs'. We can load: json, js, mjs`

**Comment by connor4312** [comment]
If you use `.mjs`, you cannot use common JS exports, and instead must use ES module imports/exports, for example: https://github.com/microsoft/vscode-extension-samples/blob/main/helloworld-test-cli-sample/.vscode-test.mjs
